apiVersion: v1
kind: Pod
metadata: 
  name: nop-db
  labels: 
    app: nop-db
    engine: postgres
spec:
  containers: 
    - name: nop-db
      image: postgres:16
      env: 
        - name: POSTGRES_PASSWORD
          value: neelu123
        - name: POSTGRES_DB
          value: neelu
        - name: POSTGRES_USER
          value: qtneelu
      resources: 
        limits:
          memory: "512Mi"
          cpu: "1000m"
      ports: 
        -containerport: 5432        