---
- name: install tomcat 10 on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: update packages and install java 11
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present
      sudo mkdir -p /opt/tomcat
sudo tar xzvf apache-tomcat-10.1.26.tar.gz -C /opt/tomcat --strip-components=1