apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: back-rs
  labels:
    app: back
    topic: resources
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - back
  template:
    metadata:
      labels:
        app: back
        topic: resources
    spec:
      containers:
        - name: back-cont
          image: nginx
          ports:
            - containerPort: 80